#!/bin/bash

if [[ ! -d /etc/nginx/ssl ]]
then
  mkdir -p /etc/nginx/ssl
  openssl req \
    -x509 \
    -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/key.pem \
    -out /etc/nginx/ssl/cert.pem \
    -days 3650 \
    -nodes \
    -subj '/CN=localhost'
fi

envsubst '$ORIGIN_SERVER' < /etc/nginx/dev.conf.template > /etc/nginx/conf.d/dev.conf

if [[ -z $1 ]]
then
  exec nginx -g 'daemon off;'
else
  exec $@
fi
